import { siteConfig } from "@/lib/site";

/**
 * Social share image settings. The images themselves are generated by
 * app/opengraph-image.tsx and app/twitter-image.tsx (see lib/og.tsx).
 */
export const socialImage = {
  width: 1200,
  height: 630,
  alt: `${siteConfig.name} — Long-term digital growth and marketing`,
  openGraphPath: "/opengraph-image",
  twitterPath: "/twitter-image",
} as const;
